<a href="https://colab.research.google.com/github/Abdullah5277/Deep-Learning/blob/main/Lstm_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('qoute_dataset.csv')

In [ ]:
quotes=df['quote']

In [ ]:
quotes=quotes.str.lower()

In [ ]:
quotes

0       “the world as we have created it is a process ...
1       “it is our choices, harry, that show what we t...
2       “there are only two ways to live your life. on...
3       “the person, be it gentleman or lady, who has ...
4       “imperfection is beauty, madness is genius and...
                              ...
3033        the past beats inside me like a second heart.
3034    damn, claire. warn a guy before you do a face-...
3035    can you be a girl for a few seconds?""i'm alwa...
3036    that's what fiction is for. it's for getting a...
3037    if we have no peace, it is because we have for...
Name: quote, Length: 3038, dtype: object

In [ ]:
import string
translator=str.maketrans('','',string.punctuation)
quotes=quotes.apply(lambda x:x.translate(translator))

In [ ]:
quotes

0       “the world as we have created it is a process ...
1       “it is our choices harry that show what we tru...
2       “there are only two ways to live your life one...
3       “the person be it gentleman or lady who has no...
4       “imperfection is beauty madness is genius and ...
                              ...
3033         the past beats inside me like a second heart
3034    damn claire warn a guy before you do a facepla...
3035    can you be a girl for a few secondsim always a...
3036    thats what fiction is for its for getting at t...
3037    if we have no peace it is because we have forg...
Name: quote, Length: 3038, dtype: object

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
VocabSize=1000
tokenizer=Tokenizer(num_words=VocabSize)
tokenizer.fit_on_texts(quotes)

In [ ]:


sequence=tokenizer.texts_to_sequences(quotes)

In [ ]:
for i in range (3):
  print(quotes[i])
  print( sequence[i])

“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”
[713, 62, 29, 19, 16, 946, 10, 7, 5, 8, 70, 293, 10, 145, 12, 809, 104, 752, 70]
“it is our choices harry that show what we truly are far more than our abilities”
[947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70]
“there are only two ways to live your life one is as though nothing is a miracle the other is as though everything is a miracle”
[14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1, 101, 7, 29, 329, 126, 7, 5]

In [ ]:

X=[]
y=[]
for seq in sequence:
  for i in range(1,len(seq)):
    input_seq=seq[i]
    output_seq=seq[i]
    X.append(input_seq)
    y.append(output_seq)

In [ ]:
len(X)

71115

In [ ]:
len(y)

71115

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Calculate the maximum sequence length from the original list of list sequences
maxlen = max(len(seq) for seq in sequence)
print(f"Maximum sequence length: {maxlen}")

# Pad sequences to ensure uniform length using the calculated maxlen
padded_sequences = pad_sequences(sequence, maxlen=maxlen, padding='pre')

print("Padded sequences shape:", padded_sequences.shape)
display(padded_sequences)

Maximum sequence length: 579
Padded sequences shape: (3038, 579)

array([[  0,   0,   0, ..., 104, 752,  70],
       [  0,   0,   0, ...,  52,  54,  70],
       [  0,   0,   0, ..., 126,   7,   5],
       ...,
       [  0,   0,   0, ..., 846, 190,  26],
       [  0,   0,   0, ...,  17,   1, 174],
       [  0,   0,   0, ...,   3, 169, 101]], dtype=int32)

In [ ]:
padded_sequences[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0, 713,  62,  29,  19,  16, 946,  10,   7,   5,   8,  70, 293,
        10, 145,  12, 809, 104, 752,  70], dtype=int32)

In [ ]:
y=np.array(y)